domain: rit-construct-makerspace.github.io
baseurl: /team-website/

collections:
  fourups:
    output: true

defaults:
  - scope:
      path: ""
      type: "fourups"
    values:
      layout: "fourup"