baseurl: /team-website
url: https://rit-construct-makerspace.github.io

collections:
  fourups:
    output: true

defaults:
  - scope:
      path: ""
      type: "fourups"
    values:
      layout: "fourup"